//
//  HomeProductsInteractor.swift
//  Merk2
//
//  Created Adrian Jacobo on 07/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeProductsInteractor: HomeProductsInteractorProtocol {

    weak var presenter: HomeProductsPresenterProtocol?
}
