//
//  HomeProductsViewController.swift
//  Merk2
//
//  Created Adrian Jacobo on 07/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeProductsViewController: UIViewController, HomeProductsViewProtocol, UITableViewDelegate, UITableViewDataSource {
    func StoreProducts(arreglo: [StoreData]) {
        stores = arreglo
        tableproducts.reloadData()
    }
    
    func StoreProductserror(message: String) {
        let alert = UIAlertController(title: "No hay información", message: "Error", preferredStyle: .alert)
        alert.addAction(UIAlertAction(title:"Continua", style: .default, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return stores.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let products = tableView.dequeueReusableCell(withIdentifier: "products") as? products{
            products.title.text = stores[indexPath.row].nombre
            products.content.text = stores[indexPath.row].descripcion
            products.price.text = stores[indexPath.row].horario
            if let urlImg = URL(string: stores[indexPath.row].imagen){
                products.imaproducts.af.setImage(withURL: urlImg)
            }
            return products
        }
        return UITableViewCell()
    }
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        self.presenter?.navigateDetailStore(data: self.stores[indexPath.row])
    }
    @IBOutlet weak var tableproducts: UITableView!
    
	var presenter: HomeProductsPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationController?.navigationBar.isHidden = true
        tableproducts.delegate = self
        tableproducts.dataSource = self
        tableproducts.register(UINib(nibName: "products", bundle: nil), forCellReuseIdentifier: "products")
        tableproducts.reloadData()
        presenter?.DataProducts()
    }
    var stores:[StoreData] = []

}

