//
//  HomeProductsRouter.swift
//  Merk2
//
//  Created Adrian Jacobo on 07/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeProductsRouter: HomeProductsWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HomeProductsViewController(nibName: nil, bundle: nil)
        let interactor = HomeProductsInteractor()
        let router = HomeProductsRouter()
        let presenter = HomeProductsPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    func navigateDetailStore(data:StoreData){
        let detailstore = DetailStoreRouter.createModule(data: data)
        viewController?.navigationController?.pushViewController(detailstore, animated: true)
    }
    
}
