//
//  HomeProductsPresenter.swift
//  Merk2
//
//  Created Adrian Jacobo on 07/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeProductsPresenter: HomeProductsPresenterProtocol {

    weak private var view: HomeProductsViewProtocol?
    var interactor: HomeProductsInteractorProtocol?
    private let router: HomeProductsWireframeProtocol

    init(interface: HomeProductsViewProtocol, interactor: HomeProductsInteractorProtocol?, router: HomeProductsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
