//
//  HomeProductsProtocols.swift
//  Merk2
//
//  Created Adrian Jacobo on 07/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeProductsWireframeProtocol: class {

}
//MARK: Presenter -
protocol HomeProductsPresenterProtocol: class {

}

//MARK: Interactor -
protocol HomeProductsInteractorProtocol: class {

  var presenter: HomeProductsPresenterProtocol?  { get set }
}

//MARK: View -
protocol HomeProductsViewProtocol: class {

  var presenter: HomeProductsPresenterProtocol?  { get set }
}
