//
//  HomeProductsProtocols.swift
//  Merk2
//
//  Created Adrian Jacobo on 07/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeProductsWireframeProtocol: AnyObject {
    func navigateDetailStore()
}
//MARK: Presenter -
protocol HomeProductsPresenterProtocol: AnyObject {
    func navigateDetailStore()
    
}

//MARK: Interactor -
protocol HomeProductsInteractorProtocol: AnyObject {

  var presenter: HomeProductsPresenterProtocol?  { get set }
}

//MARK: View -
protocol HomeProductsViewProtocol: AnyObject {

  var presenter: HomeProductsPresenterProtocol?  { get set }
}
