//
//  ProfileProtocols.swift
//  Merk2
//
//  Created Adrian Jacobo on 13/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ProfileWireframeProtocol: AnyObject {
    func navigateGoToLogin()
}
//MARK: Presenter -
protocol ProfilePresenterProtocol: AnyObject {
    func navigateGoToLogin()
    func profile()
    func profileSucces(data:DataProfileUser, phone:String)
    func profileError(message:String)
}

//MARK: Interactor -
protocol ProfileInteractorProtocol: AnyObject {

  var presenter: ProfilePresenterProtocol?  { get set }
    func profile()
}

//MARK: View -
protocol ProfileViewProtocol: AnyObject {

  var presenter: ProfilePresenterProtocol?  { get set }
    func profileSucces(data:DataProfileUser, phone:String)
    func profileError(message:String)
}
