//
//  ProfileViewController.swift
//  Merk2
//
//  Created Adrian Jacobo on 13/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AlamofireImage

class ProfileViewController: UIViewController {
    @IBOutlet weak var imagen: UIImageView!
    @IBOutlet weak var user: UILabel!
    @IBOutlet weak var completname: UILabel!
    @IBOutlet weak var phone: UILabel!
    @IBOutlet weak var mail: UILabel!
    @IBOutlet weak var close: UIButton!
    
	var presenter: ProfilePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        configUI()
        
    }
    
    @IBAction func close(_ sender: Any) {
        presenter?.navigateGoToLogin()
        let det = UserDefaults.standard
        det.set(nil, forKey: "phone")
    }
        
    func configUI(){
        imagen.layer.cornerRadius = imagen.frame.height / 2
        close.layer.cornerRadius = close.frame.height / 2
        presenter?.profile()
    }
}

extension ProfileViewController:ProfileViewProtocol{
    func profileSucces(data:DataProfileUser, phone:String){
        if let imgUrl = URL(string: data.imagen){
            self.imagen.af.setImage(withURL: imgUrl)
        }
        self.user.text = "Usuario: \(data.usuario)"
        self.completname.text = "Nombre del usuario: \(data.nombre)"
        self.mail.text = "Correo electrónico: \(data.correo)"
        self.phone.text = "Teléfono: \(phone)"
    }
    
    func profileError(message:String){
        let alert = UIAlertController(title: "Error", message: message, preferredStyle: .alert)
        alert.addAction(UIAlertAction(title: "ok", style: .default, handler: nil))
        self.present(alert, animated: true, completion: nil)
    }
}
