//
//  ProfileRouter.swift
//  Merk2
//
//  Created Adrian Jacobo on 13/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileRouter: ProfileWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ProfileViewController(nibName: nil, bundle: nil)
        let interactor = ProfileInteractor()
        let router = ProfileRouter()
        let presenter = ProfilePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func navigateGoToLogin(){
        if let tabBar = viewController?.tabBarController as? TabBarHome{
            tabBar.controllers.removeAll()
            tabBar.viewControllers = tabBar.controllers.map({ controller in
                return UINavigationController(rootViewController: controller)
            })
            tabBar.tabBar.removeFromSuperview()
            let profile = LoginRouter.createModule()
            viewController?.navigationController?.setViewControllers([profile], animated: true)
        }
        
    }
}
