//
//  ProfileProtocols.swift
//  Merk2
//
//  Created Adrian Jacobo on 13/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ProfileWireframeProtocol: class {
    func navigateGoToLogin()
}
//MARK: Presenter -
protocol ProfilePresenterProtocol: class {
    func navigateGoToLogin()
}

//MARK: Interactor -
protocol ProfileInteractorProtocol: class {

  var presenter: ProfilePresenterProtocol?  { get set }
}

//MARK: View -
protocol ProfileViewProtocol: class {

  var presenter: ProfilePresenterProtocol?  { get set }
}
