//
//  RegisterProtocols.swift
//  Merk2
//
//  Created Adrian Jacobo on 07/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol RegisterWireframeProtocol: class {

}
//MARK: Presenter -
protocol RegisterPresenterProtocol: class {

}

//MARK: Interactor -
protocol RegisterInteractorProtocol: class {

  var presenter: RegisterPresenterProtocol?  { get set }
}

//MARK: View -
protocol RegisterViewProtocol: class {

  var presenter: RegisterPresenterProtocol?  { get set }
}
