//
//  LoginPresenter.swift
//  Merk2
//
//  Created Adrian Jacobo on 06/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginPresenter: LoginPresenterProtocol {

    weak private var view: LoginViewProtocol?
    var interactor: LoginInteractorProtocol?
    private let router: LoginWireframeProtocol

    init(interface: LoginViewProtocol, interactor: LoginInteractorProtocol?, router: LoginWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func login(phone:String, pass:String){
        interactor?.login(phone: phone, pass: pass)
    }
    
    func loginError(message: String) {
        view?.loginError(message: message)
    }
    
    func loginSucces(message: String) {
        view?.loginSucces(message: message)
    }
    
    func navigateRegister(){
        router.navigateRegister()
    }
}
