//
//  LoginInteractor.swift
//  Merk2
//
//  Created Adrian Jacobo on 06/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LoginInteractor: LoginInteractorProtocol {

    weak var presenter: LoginPresenterProtocol?
    
    func login(phone:String, pass:String){
        let url = APIs().getURL(type: .general)
        let complement = APIs().getURL(type: .login)
        let params = ["phone" : phone, "pass" : pass]
        
        Services().request(url, complemet: complement, method: .post, params: params, model: BasicResponse.self){response, error in
            if let responseData = response{
                if responseData.success{
                    self.presenter?.loginSucces(message: responseData.mensaje)
                }else{
                    self.presenter?.loginError(message: responseData.mensaje)
                }
            }else{
                self.presenter?.loginError(message: "Error en el servidor, favor de intentar mas tarde")
            }
        }
    }
}
