//
//  LaunchPresenter.swift
//  Merk2
//
//  Created Adrian Jacobo on 06/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchPresenter: LaunchPresenterProtocol {

    weak private var view: LaunchViewProtocol?
    var interactor: LaunchInteractorProtocol?
    private let router: LaunchWireframeProtocol

    init(interface: LaunchViewProtocol, interactor: LaunchInteractorProtocol?, router: LaunchWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func goToLogin(){
        router.goToLogin()
    }
}
