//
//  LaunchViewController.swift
//  Merk2
//
//  Created Adrian Jacobo on 06/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchViewController: UIViewController, LaunchViewProtocol {

	var presenter: LaunchPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        self.presenter?.navegaALogin()
    }
    
}
