//
//  LaunchRouter.swift
//  Merk2
//
//  Created Adrian Jacobo on 06/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LaunchRouter: LaunchWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LaunchViewController(nibName: "LaunchViewController", bundle: nil)
        let interactor = LaunchInteractor()
        let router = LaunchRouter()
        let presenter = LaunchPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func goToLogin(){
        let loginView = LoginRouter.createModule()
        viewController?.navigationController?.pushViewController(loginView, animated: true)
    }
    
    func goToHome(){
        let homeView = TabBarHome()
        viewController?.navigationController?.pushViewController(homeView, animated: true)
    }
}
