//
//  ShopProductsProtocols.swift
//  Merk2
//
//  Created Gerardo on 25/11/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ShopProductsWireframeProtocol: class {

}
//MARK: Presenter -
protocol ShopProductsPresenterProtocol: class {

}

//MARK: Interactor -
protocol ShopProductsInteractorProtocol: class {

  var presenter: ShopProductsPresenterProtocol?  { get set }
}

//MARK: View -
protocol ShopProductsViewProtocol: class {

  var presenter: ShopProductsPresenterProtocol?  { get set }
}
