//
//  ShopProductsViewController.swift
//  Merk2
//
//  Created Gerardo on 25/11/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import AlamofireImage

class ShopProductsViewController: UIViewController, ShopProductsViewProtocol {
	var presenter: ShopProductsPresenterProtocol?
    var shoping: [DataProducts] = []
    @IBOutlet weak var tableShopProducts: UITableView!
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
        tableShopProducts.delegate = self
        tableShopProducts.dataSource = self
        tableShopProducts.register(UINib(nibName: "products", bundle: nil), forCellReuseIdentifier: "products")
        tableShopProducts.reloadData()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        self.getProducts()
    }
    @IBAction func clearCar(_ sender: Any) {
        shoping.removeAll()
        let userDefault = UserDefaults.standard
        userDefault.set(nil, forKey: "shoppingCart")
        tableShopProducts.reloadData()
    }
    
    func getProducts(){
        let userDefaults = UserDefaults.standard
        if let shoppingCartData = userDefaults.object(forKey: "shoppingCart") as? Data{
            if let shoppingCart = try? JSONDecoder().decode(ProductsCart.self, from: shoppingCartData){
                self.shoping = shoppingCart.cart
                tableShopProducts.reloadData()
            }
        }
    }
}
extension ShopProductsViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        shoping.count
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let buys = tableShopProducts.dequeueReusableCell(withIdentifier: "products") as? products{
            buys.title.text = shoping[indexPath.row].nombre
            buys.content.text = shoping[indexPath.row].descripcion
            buys.price.text = "$\(shoping[indexPath.row].precio)"
            if let shopProd = URL(string: shoping[indexPath.row].imagen){
                buys.imaproducts.af.setImage(withURL: shopProd)
            }
            return buys
        }
        return UITableViewCell()
    }
}

