//
//  ShopProductsPresenter.swift
//  Merk2
//
//  Created Gerardo on 25/11/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ShopProductsPresenter: ShopProductsPresenterProtocol {

    weak private var view: ShopProductsViewProtocol?
    var interactor: ShopProductsInteractorProtocol?
    private let router: ShopProductsWireframeProtocol

    init(interface: ShopProductsViewProtocol, interactor: ShopProductsInteractorProtocol?, router: ShopProductsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
