//
//  DetailProductRouter.swift
//  Merk2
//
//  Created Gerardo on 17/11/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailProductRouter: DetailProductWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(data: DataProducts) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DetailProductViewController(nibName: nil, bundle: nil)
        let interactor = DetailProductInteractor()
        let router = DetailProductRouter()
        let presenter = DetailProductPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        view.data = data
        
        return view
    }
}
