//
//  DetailProductPresenter.swift
//  Merk2
//
//  Created Gerardo on 17/11/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailProductPresenter: DetailProductPresenterProtocol {

    weak private var view: DetailProductViewProtocol?
    var interactor: DetailProductInteractorProtocol?
    private let router: DetailProductWireframeProtocol

    init(interface: DetailProductViewProtocol, interactor: DetailProductInteractorProtocol?, router: DetailProductWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
