//
//  DetailProductProtocols.swift
//  Merk2
//
//  Created Gerardo on 17/11/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DetailProductWireframeProtocol: AnyObject {
    func goToLogin()
}
//MARK: Presenter -
protocol DetailProductPresenterProtocol: AnyObject {
    func goToLogin()
}

//MARK: Interactor -
protocol DetailProductInteractorProtocol: AnyObject {

  var presenter: DetailProductPresenterProtocol?  { get set }
}

//MARK: View -
protocol DetailProductViewProtocol: AnyObject {

  var presenter: DetailProductPresenterProtocol?  { get set }
}
