//
//  DetailProductViewController.swift
//  Merk2
//
//  Created Gerardo on 17/11/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailProductViewController: UIViewController, DetailProductViewProtocol {

	var presenter: DetailProductPresenterProtocol?

    @IBOutlet weak var imaDetProd: UIImageView!
    @IBOutlet weak var idDetProd: UILabel!
    @IBOutlet weak var nameDetProd: UILabel!
    @IBOutlet weak var categoryDetProd: UILabel!
    @IBOutlet weak var descripDetProd: UILabel!
    @IBOutlet weak var availytiDetProd: UILabel!
    @IBOutlet weak var existenceDetProd: UILabel!
    @IBOutlet weak var priceDetProd: UILabel!
    @IBOutlet weak var discountDetProd: UILabel!
    
    var data: DataProducts?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        guard let _ = data?.id else{
            return
        }
        if let imadet = URL(string: data?.imagen ?? ""){
            self.imaDetProd.af.setImage(withURL: imadet)
            
        }
        guard let price = data?.precio else{
            return
        }
        guard let id = data?.id else{
            return
        }
        guard let name = data?.nombre else{
            return
        }
        guard let category = data?.categoria else{
            return
        }
        guard let descrip = data?.descripcion else{
            return
        }
        guard let availyti = data?.disponible else{
            return
        }
        guard let existence = data?.existencias else{
            return
        }
        guard let discount = data?.descuento else{
            return
        }
        idDetProd.text = "Clave de la orden: \(id)"
        nameDetProd.text = "Platillo: \(name)"
        categoryDetProd.text = "Categoria: \(category)"
        descripDetProd.text = "Descripción: \(descrip)"
        availytiDetProd.text = "Disponibilidad: \(availyti)"
        existenceDetProd.text = "Existencia: \(existence)"
        priceDetProd.text = "Precio: $\(price)"
        discountDetProd.text = "Descuento: %\(discount)"
        
        
    }

}
