//
//  DetailProductInteractor.swift
//  Merk2
//
//  Created Gerardo on 17/11/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailProductInteractor: DetailProductInteractorProtocol {

    weak var presenter: DetailProductPresenterProtocol?
}
