//
//  DetailStoreProtocols.swift
//  Merk2
//
//  Created Gerardo on 12/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DetailStoreWireframeProtocol: AnyObject {
    func navigateDetProd(data: DataProducts)
}
//MARK: Presenter -
protocol DetailStorePresenterProtocol: AnyObject {
    func DetailProducts(id: String)
    func DetailProductserror(message: String)
    func DetailProductssucces(array:[DataProducts])
    func navigateDetProd(data: DataProducts)
}

//MARK: Interactor -
protocol DetailStoreInteractorProtocol: AnyObject {

    var presenter: DetailStorePresenterProtocol?  { get set }
    func DetailProducts(id: String)
}

//MARK: View -
protocol DetailStoreViewProtocol: AnyObject {

    var presenter: DetailStorePresenterProtocol?  { get set }
    func DetailProductserror(message: String)
    func DetailProductssucces(array:[DataProducts])
}
