//
//  DetailStoreProtocols.swift
//  Merk2
//
//  Created Gerardo on 12/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DetailStoreWireframeProtocol: class {

}
//MARK: Presenter -
protocol DetailStorePresenterProtocol: class {

}

//MARK: Interactor -
protocol DetailStoreInteractorProtocol: class {

  var presenter: DetailStorePresenterProtocol?  { get set }
}

//MARK: View -
protocol DetailStoreViewProtocol: class {

  var presenter: DetailStorePresenterProtocol?  { get set }
}
