//
//  DetailStoreInteractor.swift
//  Merk2
//
//  Created Gerardo on 12/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailStoreInteractor: DetailStoreInteractorProtocol {
    
    weak var presenter: DetailStorePresenterProtocol?
    
    func DetailProducts(id: String){
        guard let phone = UserDefaults.standard.string(forKey: "phone") else{
            return
        }
        let url = "https://api.latitudmegalopolis.com/functions/test.php?"
        let complement = "keycode=PRODUCTS"
        let params = ["phone" : phone, "idStore" :id ]
        
        Services().request(url, complemet: complement, method: .post, params: params, model: Products.self){response, error in
            if let respon = response{
                if respon.success{
                    let data = respon.data
                    self.presenter?.DetailProductssucces(array: data)
                }else{
                    self.presenter?.DetailProductserror(message: "No se encontró información")
                }
            }else{
                self.presenter?.DetailProductserror(message: "Error en el servidor, favor de intentar mas tarde")
            }
        }
    }
}
