//
//  DetailStoreViewController.swift
//  Merk2
//
//  Created Gerardo on 12/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailStoreViewController: UIViewController, DetailStoreViewProtocol, UITableViewDelegate, UITableViewDataSource {
    var presenter: DetailStorePresenterProtocol?
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 2
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let products = tableView.dequeueReusableCell(withIdentifier: "products") as? products{
//            products.title.text = product[indexPath.row]
//            products.content.text = subproduct[indexPath.row]
//            products.price.text = "Abierto de:\(price[indexPath.row])"
            return products
        }
        return UITableViewCell()
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        TabDescripProcucts.delegate = self
        TabDescripProcucts.dataSource = self
        TabDescripProcucts.register(UINib(nibName: "products", bundle: nil), forCellReuseIdentifier: "products")
        TabDescripProcucts.reloadData()

        if let urlImg = URL(string: data?.imagen ?? ""){
            self.imaproduct.af.setImage(withURL: urlImg)
         
        }
        name.text = data?.nombre
        clas.text = data?.descripcion
        time.text = data?.horario
    }
    @IBAction func botonregresa(_ sender: Any) {
        navigationController?.popViewController(animated: true)
    }
    @IBOutlet weak var TabDescripProcucts: UITableView!
    
    var data: StoreData?
  
    
    @IBOutlet weak var name: UILabel!
    @IBOutlet weak var clas: UILabel!
    @IBOutlet weak var time: UILabel!
    @IBOutlet weak var imaproduct: UIImageView!
}
