//
//  DetailStoreInteractor.swift
//  Merk2
//
//  Created Gerardo on 12/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailStoreInteractor: DetailStoreInteractorProtocol {

    weak var presenter: DetailStorePresenterProtocol?
}
