//
//  SearchViewController.swift
//  Merk2
//
//  Created Adrian Jacobo on 13/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SearchViewController: UIViewController, SearchViewProtocol {

	var presenter: SearchPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
