//
//  SearchProtocols.swift
//  Merk2
//
//  Created Adrian Jacobo on 13/10/21.
//  Copyright © 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SearchWireframeProtocol: class {

}
//MARK: Presenter -
protocol SearchPresenterProtocol: class {

}

//MARK: Interactor -
protocol SearchInteractorProtocol: class {

  var presenter: SearchPresenterProtocol?  { get set }
}

//MARK: View -
protocol SearchViewProtocol: class {

  var presenter: SearchPresenterProtocol?  { get set }
}
